markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables", "strikethrough"]
permalink: /:year/:month/:day/:title 
title: geng bo
url: http://www.gblyz.cn
subscribe: http://gblyz.cn/atom.xml
exclude: [ README.md, newpost.rb ]
domain: gblyz.cn
author: geng bo
email: gengbo1014@gmail.com
twitterID: 
googleAnalyticsID: 
disqusShortname: gameboy120
