markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables", "strikethrough"]
permalink: /:year/:month/:day/:title 
title: geng bo
url: http://www.gblyz.cn
githubEditBaseURL: https://github.com/gameboy120/gameboy120.github.com/edit/master/
subscribe: http://ztpala.com/atom.xml
exclude: [ README.md, newpost.rb ]
domain: gblyz.com
author: geng bo
email: gengbo1014@gmail.com
twitterID: 
googleAnalyticsID: 
disqusShortname: gameboy120
timezone: America/New_York
